### ISSUE TITLE
Bugs Version 17.04.2015 11:43 Uhr

### ISSUE THREAD

**Issue by Sjaele** [GWRon/TVTower#23]
@Videokassetten

Die angezeigte Höhe der Serienepisoden stimmt nicht mit dem "Anklicken" überein

@Werbungserneuerung

Werbungsangebot wird während des Aufenthaltes im Werbungsraum erneuert.

@KI-Avatare unsichtbar

@Attentäter Endlosschleife

Bei Vertauschung des Raumes auf KI-Chefbüro gerät der Attentäter in eine Endlosschleife.

**Comment by GWRon** [comment]
Diese Bugs dann naechstes mal einzeln eintragen. Dann kann ich die fehler einzeln "schliessen". 

Mit der derzeitigen Fassung kann ich ja nur alle auf einmal zumachen.


Achso...und wenn dir github nicht gefaellt, kannst du auch einfach per mail Antworten wie diese hier verfassen (gerade im Auto nach Leipzig...Runde grillen).
