### ISSUE TITLE
Vor Tuer wartende Personen werden unsichtbar 

### ISSUE THREAD

**Issue by GWRon** [GWRon/TVTower#25]
Von SpeedMinister:
> Person "IA" wird während sie vor anderem Raum wartet unsichtbar. Türe bewegt sich dann wenn unsichtbare Person Raum wieder verlässt. Betritt man den Flur später noch einmal werden wieder alle "AIs" dargestellt.

**Comment by GWRon** [comment]
Konnte ich bis jetzt noch nicht nachvollziehen. Bugreport noch eine Weile offen lassen

**Comment by Sjaele** [comment]
Ist mir beim Werbungstesten aufgefallen. Konnte ich nicht wiederholen. Trat aber ein und endete dann einfach nach mehrfachem Betreten und Verlassen.
Raum war besetzt. Irgendwann öffnete sich die Tür aber keine Figur sichtbar.

Hausmeister etc. war sichtbar.
