### ISSUE TITLE
Aktualität kann nach Sendungsausstrahlung höher sein als das neue Maximum

### ISSUE THREAD

**Issue by sushidelic** [GWRon/TVTower#35]
- nach dem eine Sendung ausgestrahlt wurde sinkt ja die Aktualität
- bei Sendungen die sich schnell erholen kann dann die Aktualität höher sein als das Maximum (z.bsp. 0,65 von 0,64) 
- wird scheinbar bei Tageswechsel "korrigiert"
- ist das so gewollt?

**Comment by GWRon** [comment]
Die Aktualitaet kann nicht hoeher sein als das Maximum. Im Code befindet sich keine Code-Zeile die "topicality" modifiziert und "maxTopicality" ignoriert.

```BlitzMax
game.programme.programmedata.bmx

Zeile 743 ( GetTopicality:Float() )
if topicality < 0 then topicality = GetMaxTopicality()

Zeile 793 ( CutTopicality:Int(cutFactor:float=1.0) )
topicality:* Min(1.0,  cutFactor * GetProgrammeDataCollection().wearoffFactor * GetGenreWearoffModifier() * GetWearoffModifier() )

Zeile 810 ( RefreshTopicality:Int() )
topicality = Min(GetMaxTopicality(), topicality*GetProgrammeDataCollection().refreshFactor*self.GetGenreRefreshModifier()*self.GetRefreshModifier())
```

Was allerdings passieren kann: Ein Programm "erholt" sich ... und kurz darauf sinkt die maximale Aktualitaet durch Alterung des Programmes. ... ich werde "GetTopicality()" nun das Minimum von "derzeit" und "max" zurueckgeben lassen ...
