### ISSUE TITLE
Trailer - Programm im Sendeplan

### ISSUE THREAD

**Issue by sushidelic** [GWRon/TVTower#38]
nach entfernen eines Trailes aus dem Programm wird der Status "Programm im Sendeplan" geändert und kann somit falsch sein. -> Programm ist im Sendeplan, wird aber nicht mehr als solches gekennzeichnet.

**Comment by GWRon** [comment]
Nachstellen:
- Programm im Planer als "Film" platzieren (Meldung "im Programmplan" vorhanden)
- Programm im Planer als "Trailer" platzieren (Meldung "im Programmplan" vorhanden)
- Trailer wieder entfernen, Meldung im verbleibenden Film nicht mehr vorhanden

**Comment by GWRon** [comment]
Problem war, dass eine Methode die uebergebene Sendung zuruecklieferte, statt die angeforderte erste/letzte Instanz der betreffenden Werbung/Programmlizenz.

Das zurueckgelieferte Element hatte - wenn geloescht - schon zurueckgesetzte Variablen ("programmedDay" und "programmedHour") was dann zu einer falschen "SetPlanned(latestHour)" fuehrte.

Ursache gefunden und Fehler behoben. Danke fuers aufspueren @sushidelic
