### ISSUE TITLE
KI: Kauft ständig Nachrichten

### ISSUE THREAD

**Issue by sushidelic** [GWRon/TVTower#39]
Laut meinen KI logs und auch Ingame scheint die KI extrem viel in Nachrichten zu investieren.
Dies ist so richtig Mad TV Style :)

Bsp. KI gibt am ersten Tag ~ 100.000 Euro für Nachrichten aus was aber bei derzeitiger Spielversion etwas übertrieben ist, da man auch mit schlechten Nachrichten "Normale" Einschaltquoten erreicht.

(Im Original hat man ohne Nachrichten so gut wie gar keine Zuschauer gehabt - glaube ich)

**Comment by GWRon** [comment]
Kauft "aktuell" ausgeglichener
