### ISSUE TITLE
Bei Laden eines Speicherstandes stürzt Spiel ab.

### ISSUE THREAD

**Issue by Sjaele** [GWRon/TVTower#40]
Beim Laden eines Speicherstandes stürzt das Spiel mit der Meldung

"Exception_Int_Divide_by_Zero"

ab.

Ich kann grade leider nur über wine spielen, weiß also nicht, ob's daran liegt.

**Comment by sushidelic** [comment]
bei mir auch :)

**Comment by GWRon** [comment]
Nein... die "null"-Betty ist normal, da wir noch nix zu Betty im Speicherstand hinterlegen.

Den div/0 error habe ich ja mit dem letzten Patch geschlossen.
