### ISSUE TITLE
Bei verkaufter Serie bleiben die Episoden im Programmplaner

### ISSUE THREAD

**Issue by Sjaele** [GWRon/TVTower#41]
Ich habe eine Serie verkauft.
Danach waren die Episoden noch im Programmplaner.
Auch nach dem Tageswechsel.

Lasse ich die Episoden weiterhin im Programmplan, stürzt das Spiel bei Sendungsbeginn kommentarlos ab.

Kein Eintrag ins Log.

wiederholbar mit verschiedenen Serien.

**Comment by sushidelic** [comment]
Kann ich bestädigen. ohne Tageswechsel. Dabei habe ich beim verkauf auch kein Geld bekommen - Finanzstatistik +15.000 und -15.000 bei Handel mit Programmlizenzen.

**Comment by GWRon** [comment]
Schaetze, dass haengt mit ein paar Aenderungen zusammen, die Serienepisoden in der TPlayerProgrammeCollection einlagerten.

Schau ich mir morgen an, wenn ich aus dem Urlaub zurueck bin. Also morgen...

**Comment by GWRon** [comment]
Lag doch nicht an den Aenderungen ... schlicht und ergreifend wurde auf "GetData() <> null" geprueft (da frueher Serienkoepfe keinen Datenblock hatten ...), nun wird korrekt "GetSubLicenceCount()" genutzt und alle Unterlizenzen werden korrekt aus dem Plan geworfen.

**Comment by GWRon** [comment]
In 29fab5a9b259fdec1b6c453d858db2439a83befc gefixt.
