### ISSUE TITLE
FullScreen "True" = Programmer error! Call InitVirtualGraphics BEFORE Graphics!

### ISSUE THREAD

**Issue by sushidelic** [GWRon/TVTower#42]
bekomme beim Start von TVT im Fullscreen die Meldung: 
"Programmer error! Call InitVirtualGraphics BEFORE Graphics!"
nach Bestädigung der Meldung startet dann TVTower aber trotzdem.

v.0.2.3. Win7

**Comment by GWRon** [comment]
Kommt noch eine Meldung bezueglich DirectX oder OpenGL? Eventuell kommt es zustande, da es einen Renderpfad nicht einschlagen kann (funzt DX9 nicht, nimmt es DX7 und dann OpenGL) - dadurch kommt es zu einer falschen Auswertung der "besteht bereits ein Grafikobjekt"-Abfrage und die Notification wird ausgespuckt

**Comment by sushidelic** [comment]
Nein keine Weitere Meldung, in der vorhergehenden Version kam aber gar keine Meldung, also erst mit diesem Release. ~s~

**Comment by GWRon** [comment]
NG-Build oder meiner? 

Ich habe eigentlich nichts an diesem Code geaendert. Es ist auch keine Fehlermeldung, sondern nur eine Notiz an den Programmierer: es besteht schon ein Grafikgrundgeruest und ein neues soll es ersetzen. Das soll verhindern, dass die "virtuelle Aufloesung" falsche Umgebungsvariablen bekommt. Das wird gebraucht um bei Vollbild auf Breitbildmonitoren vom Spiel aus "Balken" einfuegen zu koennen, aber Dinge wie Mauskoordinaten korrekt zu behandeln.

**Comment by sushidelic** [comment]
v.0.2.3. Win7 16:9 - 1920x1080, auch wenn ich die Auflößung vorher auf 800x600 Umstelle kommt die Meldung. Also dein Build vom 20.06. ;) - wenn'sein NG-Build wäre hätte ich das schon erwähnt.
