### ISSUE TITLE
Sendemastkauf - Preisangabe mit "Mio" ist immer "zu teuer"

### ISSUE THREAD

**Issue by Sjaele** [GWRon/TVTower#48]
Wenn der Preis für einen neuen Sendemast in Hunderttausendern angegeben wird, klappt alles normal.
Wird der Preis jedoch in Mio angegeben, wird mir selbst bei 0,08 Mio der Sendemast als zu teuer angegeben.

**Comment by GWRon** [comment]
"Selbst bei 0.08 mio"... die muesste es dann doch als 80.000 bzw 80Tsd anzeigen.

Wann zeigt es solche Werte an?

**Comment by GWRon** [comment]
Ok... so hier auf einem PC schnell runtergeladen und Fehler reproduziert.

Generell schwankt die Ausgabe der Geldwerte-Texte... mal hab schon eine Ahnung an welcher Stelle es hakt. Muss wohl noch ein paar Tests schreiben.

**Comment by GWRon** [comment]
Gefixt
