### ISSUE TITLE
Wird Häkche bei "Filme >Startjahr" ignoriert?

### ISSUE THREAD

**Issue by Sjaele** [GWRon/TVTower#58]
Vermute ich jetzt nur mal, da mir noch keine Filme > Startjahr aufgefallen sind und auch bei Ausverkauf die Filme lange (mehrere Spieltage) nicht nachgefüllt werden.

**Comment by GWRon** [comment]
Ich koennte das jetzt reaktivieren, habe aber festgestellt, dass dann ja auch Filme mit erscheinen, die eigentlich kurz darauf erscheinen sollten. Das macht die Option irgendwie "sinnlos".

**Comment by Sjaele** [comment]
Ich koennte das jetzt reaktivieren, habe aber festgestellt, dass dann
ja auch Filme mit erscheinen, die eigentlich kurz darauf erscheinen
sollten. Das macht die Option irgendwie "sinnlos". 

	—

	Grossser plauer Schpassssvoggel. :)

 Profitieren Sie von der sicheren E-Mail-Übertragung Ihrer Daten mit
einer kostenlosen E-Mail-Adresse der Telekom.
www.t-online.de/email-kostenlos

**Comment by GWRon** [comment]
Ich meinte das ernst!

Die Option ist ja dafuer gedacht, jedewede zukuenftige Programmlizenz schon "jetzt" verfuegbar zu gestalten.

Es kommen also nie neue Programme hinzu. Da schon zu Anbeginn ein Portfolio aus nur "ueber-neuen" Programmen entstehen kann, wird das sogar noch ueberdrehter...

**Comment by GWRon** [comment]
Die aktuelle Fassung hat das Haekchen "draussen" (und reagiert aufs "anhaken"), ich denke aber, die Option sollte irgendwann "wegfallen".

Somit erstmal gefixt.
