### ISSUE TITLE
Keine Funktion um das Spiel zu beenden

### ISSUE THREAD

**Issue by hhirsch** [GWRon/TVTower#68]
Ich habe das Spiel in Vollbild (OpenGL) gestartet und es gab keine Möglichkeit das Spiel zu beenden.
Im Handbuch konnte ich unter Tastenkürzel auch nichts finden. Beim Chef gibt es auch keine Kündigen-Funktion. Wenn ich das Tastenkürzel vom Betriebsystem zum Fenster schließen drücke, wandert mein Avatar zum Chef, aber keine Möglichkeit zu kündigen.

Es handelt sich um die aktuelle 10/2015 version von der Webseite. Ich verwende die Linuxversion ohne pulseaudio.

**Comment by GWRon** [comment]
Escape-Taste funktioniert nicht?

Klick auf [X] im Fenstermodus sollte ebenfalls einen Beenden-Dialog erstellen

Am 4. Oktober 2015 07:44:25 MESZ, schrieb Henry Hirsch <notifications@github.com>:

**Comment by hhirsch** [comment]
Escape funktionierte nicht und x gibt es im Vollbild-Modus nicht. Kanns du es nicht reproduzieren? Kannst du im OpenGL im Vollbild mit esc beenden?

**Comment by GWRon** [comment]
Ich kann hier nix reproduziereb...bin grad im kreissaal.

Funzt ESC im Fenstermodus?

Am 4. Oktober 2015 08:25:18 MESZ, schrieb Henry Hirsch <notifications@github.com>:

**Comment by hhirsch** [comment]
Also im Fenstermodus kann ich es auch nicht beenden. Weder mit der Tastenkombination zum Fenster schließen noch mit ESC. Das x gibt es nicht wirklich in xmonad (GNU/Linux Window Manager). Aber es lassen sich normalerweise Fenster mit einer Testenkombination schließen. Dann alles gute und viel Erfolg im Kreissaal.

**Comment by GWRon** [comment]
Funktionieren andere Tastenkuerzel im Spiel? Also O...ffice A...rchiv... f...ilmagentur?
Evtl klappts ja generell nicht mit den Tastaturereignissen.

**Comment by hhirsch** [comment]
Die anderen Tastenkürzel haben funktioniert. Auch das Beschleunigen der Zeit hat funktioniert.

**Comment by GWRon** [comment]
hmm also geht wohl der "beendendialog" bei dir nicht.

Spielst du mit dem aktuellsten DevPatch?

Geht die Escapetaste bei einem Fruehjahrsrelease (vor Implementierung des Escapemenues).


Geht das "Einstellungsfenster" im Startbildschirm?

**Comment by hhirsch** [comment]
Einstellungsfenster im Startbildschirm funktioniert. Ich weiß nicht welchen Release ich habe. Gepatcht habe ich nicht.

**Comment by hhirsch** [comment]
Der Release ist der aktuelle von der Webseite, heute heruntergeladen.

**Comment by GWRon** [comment]
Ich schau mir das die Tage mal an und bau Dir eventuell n SpezialBuild damit wir der Ursache auf die Schliche kommen.


Wenn du in einem Raum bist...bspweise Programmplaner, so sollte dort ein "Escape" die aktuelle Aktion abbrechen (Programm wieder fallen lassen).
wenn das nicht klappt, dann wird die Escapetaste nicht richtig verarbeitet.
wenns klappt...kann liegt es an der Spiellogik (Escapemenuebehandlung oder KeyManager).

Immer wieder interessant was fuer Fehler so auftreten koennen :-)

**Comment by GWRon** [comment]
Der gerade veroeffentlichte "DevPatch" (im "Aktuelle Version"-Thread des Forums) enthaelt nun erstmal eine "STRG+C"->"Spiel zwingend beenden"-Funktion

Damit solltest Du erstmal etwas entspannter spielen koennen.

Den genauen Fehler versuchen wir dann die Tage zu lokalisieren.
