### ISSUE TITLE
Problem with series in program-schedule

### ISSUE THREAD

**Issue by bassslave** [GWRon/TVTower#75]
In v0.3.2 Build "29.05.16 01:54" I can't put episode >8 of any television series into the schedule.
The mouseclick just doesn't do anything.

**Comment by GWRon** [comment]
Yes it is known...and fixed already in the code (and dev builds...which are available in the forums at gamezworld.de/phpforum)

**Comment by GWRon** [comment]
Fixed in b29b1728c22f97192fd60325a1de239b0ecb6331
